# Generated by Django 3.0.7 on 2020-06-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='new_url',
            field=models.URLField(default='xyz', max_length=50, null=True),
        ),
    ]
