# Generated by Django 3.0.7 on 2020-06-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200623_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='new_url',
            field=models.CharField(default='xyz', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='og_url',
            field=models.CharField(max_length=500),
        ),
    ]
