# Generated by Django 3.0.7 on 2020-06-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200623_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmodel',
            name='og_url',
        ),
        migrations.AddField(
            model_name='urlmodel',
            name='old_url',
            field=models.CharField(default='zyx', max_length=500),
        ),
    ]
