# Generated by Django 3.0.7 on 2020-06-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200623_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='old_url',
            field=models.CharField(max_length=500),
        ),
    ]
