# Generated by Django 3.0.7 on 2020-06-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200624_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='new_url',
            field=models.URLField(default='xyz', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='old_url',
            field=models.URLField(max_length=500),
        ),
    ]
