# Generated by Django 3.0.7 on 2020-06-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200625_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='new_url',
            field=models.CharField(default='xyz', max_length=16, null=True),
        ),
    ]
