# Generated by Django 4.0.4 on 2023-01-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200625_1937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UrlModel',
        ),
    ]
